[2024-07-31T03:12:20.872+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-31T03:12:20.895+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline.data_cleansing scheduled__2024-07-31T03:10:00+00:00 [queued]>
[2024-07-31T03:12:20.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline.data_cleansing scheduled__2024-07-31T03:10:00+00:00 [queued]>
[2024-07-31T03:12:20.904+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-31T03:12:20.916+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_cleansing> on 2024-07-31 03:10:00+00:00
[2024-07-31T03:12:20.925+0000] {standard_task_runner.py:64} INFO - Started process 14813 to run task
[2024-07-31T03:12:20.928+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Pipeline', 'data_cleansing', 'scheduled__2024-07-31T03:10:00+00:00', '--job-id', '646', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpkft7_n7g']
[2024-07-31T03:12:20.931+0000] {standard_task_runner.py:91} INFO - Job 646: Subtask data_cleansing
[2024-07-31T03:12:20.990+0000] {task_command.py:426} INFO - Running <TaskInstance: Pipeline.data_cleansing scheduled__2024-07-31T03:10:00+00:00 [running]> on host f17ca52b44b4
[2024-07-31T03:12:21.081+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline' AIRFLOW_CTX_TASK_ID='data_cleansing' AIRFLOW_CTX_EXECUTION_DATE='2024-07-31T03:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-31T03:10:00+00:00'
[2024-07-31T03:12:21.084+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-31T03:12:21.430+0000] {logging_mixin.py:188} INFO - 

            fecha      hora  ... tipo_de_servicio franja horaria
0  02/01/2021  20:45:00  ...       PARTICULAR          Noche

[1 rows x 9 columns]
[2024-07-31T03:12:21.444+0000] {logging_mixin.py:188} INFO - Contenido verificado del Parquet file:
[2024-07-31T03:12:21.454+0000] {logging_mixin.py:188} INFO -         fecha      hora  ... tipo_de_servicio franja horaria
0  02/01/2021  20:45:00  ...       PARTICULAR          Noche
1  03/01/2021  11:50:00  ...          PUBLICO         Ma√±ana
2  04/01/2021  13:20:00  ...       PARTICULAR          Tarde
3  04/01/2021  15:30:00  ...          OFICIAL          Tarde
4  04/01/2021  19:00:00  ...       PARTICULAR          Noche

[5 rows x 9 columns]
[2024-07-31T03:12:21.455+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-31T03:12:21.456+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/funtions.py", line 160, in data_cleansing
    context['ti'].xcom_pull(key='temp_file_path',value=temp_file)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'value'
[2024-07-31T03:12:21.467+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Pipeline, task_id=data_cleansing, run_id=scheduled__2024-07-31T03:10:00+00:00, execution_date=20240731T031000, start_date=20240731T031220, end_date=20240731T031221
[2024-07-31T03:12:21.478+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 646 for task data_cleansing (xcom_pull() got an unexpected keyword argument 'value'; 14813)
[2024-07-31T03:12:21.504+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-31T03:12:21.531+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-31T03:12:21.533+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
