[2024-07-25T05:09:55.290+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T05:09:55.450+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline.transforms_data scheduled__2024-07-25T05:08:00+00:00 [queued]>
[2024-07-25T05:09:55.465+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline.transforms_data scheduled__2024-07-25T05:08:00+00:00 [queued]>
[2024-07-25T05:09:55.476+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-25T05:09:55.503+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transforms_data> on 2024-07-25 05:08:00+00:00
[2024-07-25T05:09:55.512+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-25T05:09:55.514+0000] {standard_task_runner.py:64} INFO - Started process 3103 to run task
[2024-07-25T05:09:55.513+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Pipeline', 'transforms_data', 'scheduled__2024-07-25T05:08:00+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpppb1gcee']
[2024-07-25T05:09:55.517+0000] {standard_task_runner.py:91} INFO - Job 223: Subtask transforms_data
[2024-07-25T05:09:55.565+0000] {task_command.py:426} INFO - Running <TaskInstance: Pipeline.transforms_data scheduled__2024-07-25T05:08:00+00:00 [running]> on host f7d3c5e5ad21
[2024-07-25T05:09:55.685+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline' AIRFLOW_CTX_TASK_ID='transforms_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T05:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T05:08:00+00:00'
[2024-07-25T05:09:55.687+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T05:09:55.698+0000] {logging_mixin.py:188} INFO - Type of data received: <class 'str'>
[2024-07-25T05:09:55.699+0000] {logging_mixin.py:188} INFO - Data received: [{'orden': '1', 'fecha': '02/01/2021', 'hora': '20:45:00', 'direcci_n': 'Calle 1 X Carrera 1', 'nro_...
[2024-07-25T05:09:55.699+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T05:09:55.700+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/funtions.py", line 23, in transform_data
    data_list=json.loads(data)
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
[2024-07-25T05:09:55.721+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Pipeline, task_id=transforms_data, run_id=scheduled__2024-07-25T05:08:00+00:00, execution_date=20240725T050800, start_date=20240725T050955, end_date=20240725T050955
[2024-07-25T05:09:55.735+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 223 for task transforms_data (Expecting property name enclosed in double quotes: line 1 column 3 (char 2); 3103)
[2024-07-25T05:09:55.769+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T05:09:55.810+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T05:09:55.814+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
