[2024-07-27T02:46:36.157+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-27T02:46:36.179+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline.transforms_data scheduled__2024-07-27T02:45:00+00:00 [queued]>
[2024-07-27T02:46:36.187+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline.transforms_data scheduled__2024-07-27T02:45:00+00:00 [queued]>
[2024-07-27T02:46:36.188+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-27T02:46:36.201+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transforms_data> on 2024-07-27 02:45:00+00:00
[2024-07-27T02:46:36.209+0000] {standard_task_runner.py:64} INFO - Started process 1434 to run task
[2024-07-27T02:46:36.212+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Pipeline', 'transforms_data', 'scheduled__2024-07-27T02:45:00+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpjwyu58rm']
[2024-07-27T02:46:36.215+0000] {standard_task_runner.py:91} INFO - Job 409: Subtask transforms_data
[2024-07-27T02:46:36.284+0000] {task_command.py:426} INFO - Running <TaskInstance: Pipeline.transforms_data scheduled__2024-07-27T02:45:00+00:00 [running]> on host 9802fafdbfe2
[2024-07-27T02:46:36.527+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline' AIRFLOW_CTX_TASK_ID='transforms_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-27T02:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-27T02:45:00+00:00'
[2024-07-27T02:46:36.529+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-27T02:46:36.767+0000] {logging_mixin.py:188} INFO - 
Datos convertido en DataFrame:
[2024-07-27T02:46:36.778+0000] {logging_mixin.py:188} INFO -    orden       fecha      hora  ...   tipo_hecho clase_vehiculo tipo_de_servicio
0     1  02/01/2021  20:45:00  ...  Volcamiento      AUTOMOVIL       PARTICULAR

[1 rows x 9 columns]
[2024-07-27T02:46:37.369+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-27T02:46:37.373+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/funtions.py", line 39, in transform_data
    dag_folder = context['dag'].folder
NameError: name 'context' is not defined
[2024-07-27T02:46:37.406+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Pipeline, task_id=transforms_data, run_id=scheduled__2024-07-27T02:45:00+00:00, execution_date=20240727T024500, start_date=20240727T024636, end_date=20240727T024637
[2024-07-27T02:46:37.447+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 409 for task transforms_data (name 'context' is not defined; 1434)
[2024-07-27T02:46:37.474+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-27T02:46:37.500+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-27T02:46:37.503+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
